# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 21:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumidorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='almuerzos/static/img/AvatarEstudiante.png', upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almuerzos.ConsumidorProfile')),
            ],
        ),
        migrations.CreateModel(
            name='FijoProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaIni', models.TimeField()),
                ('horaFin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MovilProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('precio', models.IntegerField(default=0)),
                ('avatar', models.ImageField(default='almuerzos/static/img/bread.png', upload_to='')),
                ('foto', models.ImageField(default='almuerzos/static/img/background4.png', upload_to='almuerzos/productos/')),
                ('vendidos', models.IntegerField(default=0)),
                ('enVenta', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favoritos', models.IntegerField(default=0)),
                ('avatar', models.ImageField(default='almuerzos/static/img/AvatarVendedor1.png', upload_to='')),
                ('efectivo', models.BooleanField()),
                ('debito', models.BooleanField()),
                ('credito', models.BooleanField()),
                ('junaeb', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='vendedor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='almuerzos.Vendedor'),
        ),
        migrations.AddField(
            model_name='movilprofile',
            name='userType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almuerzos.UserType'),
        ),
        migrations.AddField(
            model_name='movilprofile',
            name='vendedor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='almuerzos.Vendedor'),
        ),
        migrations.AddField(
            model_name='fijoprofile',
            name='userType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almuerzos.UserType'),
        ),
        migrations.AddField(
            model_name='fijoprofile',
            name='vendedor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='almuerzos.Vendedor'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almuerzos.Vendedor'),
        ),
        migrations.AddField(
            model_name='consumidorprofile',
            name='userType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almuerzos.UserType'),
        ),
    ]
