# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userType',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='almuerzos.UserType'),
        ),
    ]
