# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 03:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0002_auto_20170527_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumidorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('avatar', models.ImageField(default='almuerzos/static/img/AvatarEstudiante.png', upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FijoProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('avatar', models.ImageField(default='almuerzos/static/img/AvatarEstudiante.png', upload_to='')),
                ('efectivo', models.BooleanField()),
                ('debito', models.BooleanField()),
                ('credito', models.BooleanField()),
                ('junaeb', models.BooleanField()),
                ('activo', models.BooleanField(default=False)),
                ('favoritos', models.IntegerField(default=0)),
                ('horaIni', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovilProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('avatar', models.ImageField(default='almuerzos/static/img/AvatarEstudiante.png', upload_to='')),
                ('efectivo', models.BooleanField()),
                ('debito', models.BooleanField()),
                ('credito', models.BooleanField()),
                ('junaeb', models.BooleanField()),
                ('activo', models.BooleanField(default=False)),
                ('favoritos', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='userType',
        ),
        migrations.AlterField(
            model_name='usertype',
            name='type',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='movilprofile',
            name='userType',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='almuerzos.UserType'),
        ),
        migrations.AddField(
            model_name='fijoprofile',
            name='userType',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='almuerzos.UserType'),
        ),
        migrations.AddField(
            model_name='consumidorprofile',
            name='userType',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='almuerzos.UserType'),
        ),
    ]
