# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0003_auto_20170528_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almuerzos.Vendedor'),
        ),
    ]
