# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0003_auto_20170527_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumidorprofile',
            name='userType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almuerzos.UserType'),
        ),
        migrations.AlterField(
            model_name='fijoprofile',
            name='userType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almuerzos.UserType'),
        ),
        migrations.AlterField(
            model_name='movilprofile',
            name='userType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almuerzos.UserType'),
        ),
    ]
