# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0005_auto_20170529_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='foto',
            field=models.ImageField(default='almuerzos/static/img/background4.png', upload_to=''),
        ),
    ]
