# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0006_auto_20170529_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='foto',
            field=models.ImageField(default='background4.png', upload_to=''),
        ),
    ]
