# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0007_auto_20170529_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumidorprofile',
            name='avatar',
            field=models.ImageField(default='AvatarEstudiante.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='productos',
            name='avatar',
            field=models.ImageField(default='bread.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='productos',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='avatar',
            field=models.ImageField(default='AvatarVendedor1.png', upload_to=''),
        ),
    ]
